name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install flask pandas scikit-learn joblib gunicorn

      - name: Run tests (optional)
        run: echo "No tests implemented"

      - name: Build Docker Image
        run: docker build -t titanic-api .

      - name: Run Container
        run: docker run -d -p 5000:5000 titanic-api
