name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Runs when code is pushed to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # - name: Run Tests (if you have any)
    #   run: |
    #     python -m unittest discover -s tests  # Modify if you have test cases

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker login
        docker build -t himanshu8/titanic-ml-api:latest .
        docker push himanshu8/titanic-ml-api:latest

    - name: Deploy Container (Optional)
      run: |
        docker run -d -p 5000:5000 himanshu8/titanic-ml-api:latest